

export const tipodecliente=[

{
      
  "description": "Cliente",
},
{
  
  "description": "Codeudor"
} ];

export const tipodepersona=
[
    
  {
    
    "description": "Natural",
  },
  {
    
    "description": "Júridica"
  } ];

 export const codCIU = 
 
    [ "0010 Asalariados",
"0081 Sin actividad económica, solo para personas naturales",
"0082 Personas Naturales Subsidiadas por Terceros",
"0090 Rentistas de Capital, solo para personas naturales",
"0111 Producción especializada de café",
"0112 Producción especializada de flor de corte y productos de vivero",
"0112 Producción especializada de flor de corte y productos de vivero",
"0114 Producción especializada de caña de azúcar",
"0115 Producción especializada de cereales y oleaginosas",
"0116 Producción especializada de hortalizas y legumbres",
"0117 Producción especializada de frutas (excepto banano y plátano), nueces, plantas bebestibles (excepto café) y especias",
"0118 Producción especializada de otros cultivos n.c.p.",
"0119 Producción agrícola en unidades no especializadas",
"0121 Cría especializada de ganado vacuno",
"0122 Cría especializada de ganado porcino",
"0123 Cría especializada de aves de corral",
"0124 Cría especializada de ovejas, cabras, caballos, asnos, mulas y burdéganos",
"0125 Cría especializada de otros animales n.c.p. y la obtención de sus productos",
"0124 Cría especializada de ovejas, cabras, caballos, asnos, mulas y burdéganos",
"0124 Cría especializada de ovejas, cabras, caballos, asnos, mulas y burdéganos",
"0124 Cría especializada de ovejas, cabras, caballos, asnos, mulas y burdéganos",
"0140 Actividades de servicios agrícolas y ganaderos, excepto las actividades veterinarias",
"0201 Silvicultura y extracción de la madera",
"0201 Silvicultura y extracción de la madera",
"0501 Pesca y actividades de servicios relacionadas",
"0502 Acuicultura y actividades de servicios relacionadas",
"1010 Extracción y aglomeración de hulla (carbón de piedra)",
"1020 Extracción y aglomeración de carbón lignítico",
"1030 Extracción y aglomeración de turba",
"1110 Extracción de petróleo crudo y de gas natural",
"1120 Actividades de servicios relacionadas con la extracción de petróleo y gas, excepto las actividades de prospección",
"1200 Extracción de minerales de uranio y de torio",
"1310 Extracción de minerales de hierro",
"1320 Extracción de metales preciosos",
"1331 Extracción de minerales de níquel",
"1339 Extracción de otros minerales metalíferos no ferrosos, excepto níquel",
"1411 Extracción de piedra, arena y arcillas comunes",
"1412 Extracción de yeso y anhidrita",
"1413 Extracción de caolín, arcillas de uso industrial y bentonitas",
"1414 Extracción de arenas y gravas silíceas",
"1415 Extracción de caliza y dolomita",
"1421 Extracción de minerales para la fabricación de abonos y productos químicos",
"1422 Extracción de halita (sal)",
"1431 Extracción de esmeraldas",
"1432 Extracción de otras piedras preciosas y semipreciosas",
"1490 Extracción de otros minerales no metálicos n.c.p.",
"1511 Producción, procesamiento y conservación de carne y productos cárnicos",
"1512 Procesamiento y conservación de pescado y productos de pescado",
"1521 Procesamiento y conservación de frutas, legumbres y hortalizas",
"1522 Elaboración de aceites y grasas de origen vegetal y animal",
"1530 Elaboración de productos lácteos",
"1541 Elaboración de productos de molinería",
"1542 Elaboración de almidones y productos derivados del almidón",
"1543 Elaboración de alimentos preparados para animales",
"1561 Trilla de café",
"1562 Descafeinado",
"1563 Tostión y molienda del café",
"1564 Elaboración de otros derivados del café",
"1571 Fabricación y refinación de azúcar",
"1572 Fabricación de panela",
"1581 Elaboración de cacao, chocolate y productos de confitería",
"1582 Elaboración de productos de panadería",
"1583 Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares",
"1589 Elaboración de otros productos alimenticios n.c.p.",
"1591 Destilación, rectificación y mezcla de bebidas alcohólicas; producción de alcohol etílico a partir de sustancias fermentadas",
"1592 Elaboración de bebidas fermentadas no destiladas",
"1593 Producción de malta, elaboración de cervezas y otras bebidas malteadas",
"1594 Elaboración de bebidas no alcohólicas",
"1600 Fabricación de productos de tabaco",
"1710 Preparación e hilatura de fibras textiles",
"1720 Tejedura de productos textiles",
"1730 Acabado de productos textiles no producidos en la misma unidad de producción",
"1741 Confección de artículos con materiales textiles no producidos en la misma unidad, excepto prendas de vestir",
"1742 Fabricación de tapices y alfombras para pisos",
"1743 Fabricación de cuerdas, cordeles, cables, bramantes y redes",
"1749 Fabricación de otros artículos textiles n.c.p.",
"1750 Fabricación de tejidos y artículos de punto y ganchillo",
"1810 Confección de prendas de vestir, excepto prendas de piel",
"1820 Adobo y teñido de pieles",
"1910 Curtido y adobo de cueros",
"1921 Fabricación de calzado de cuero y piel, con cualquier tipo de suela, excepto el calzado deportivo",
"1922 Fabricación de calzado de materiales textiles, con cualquier tipo de suela, excepto el calzado deportivo",
"1923 Fabricación de calzado de caucho, excepto el calzado deportivo",
"1924 Fabricación de calzado de plástico, excepto el calzado deportivo",
"1925 Fabricación de calzado deportivo, incluso el moldeado",
"1926 Fabricación de partes del calzado",
"1929 Fabricación de calzado n.c.p.",
"1931 Fabricación de artículos de viaje, bolsos de mano, artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería",
"1932 Fabricación de artículos de viaje, bolsos de mano y artículos similares, elaborados en materiales sintéticos, plástico e imitaciones de cuero",
"1939 Fabricación de artículos de viaje, bolsos de mano, y artículos similares elaborados con materiales n.c.p.",
"2010 Aserrado, acepillado e impregnación de la madera",
"2020 Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles",
"2030 Fabricación de partes y piezas de carpintería para edificios y construcciones",
"2040 Fabricación de recipientes de madera",
"2090 Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería",
"2101 Fabricación de pastas celulósicas, papel y cartón.",
"2102 Fabricación de papel y cartón ondulado, fabricación de envases, empaques y de embalajes de papel y cartón",
"2109 Fabricación de otros artículos de papel y cartón",
"2211 Edición de libros, folletos y otras publicaciones",
"2212 Edición de periódicos, revistas y publicaciones periódicas",
"2213 Edición de Música",
"2219 Otros trabajos de edición",
"2220 Actividades de impresión",
"2230 Actividades de servicios relacionadas con la impresión",
"2240 Reproducción de grabaciones",
"2310 Fabricación de productos de hornos de coque",
"2321 Fabricación de productos de la refinación del petróleo, elaborados en refinería",
"2322 Elaboración de productos derivados del petróleo, fuera de refinería",
"2330 Elaboración de combustible nuclear",
"2411 Fabricación de sustancias químicas básicas, excepto abonos y compuestos inorgánicos nitrogenados",
"2412 Fabricación de abonos y compuestos inorgánicos nitrogenados",
"2413 Fabricación de plásticos en formas primarias",
"2414 Fabricación de caucho sintético en formas primarias",
"2421 Fabricación de plaguicidas y otros productos químicos de uso agropecuario",
"2422 Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas",
"2423 Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos",
"2424 Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador",
"2429 Fabricación de otros productos químicos n.c.p.",
"2430 Fabricación de fibras sintéticas y artificiales",
"2511 Fabricación de llantas y neumáticos de caucho",
"2512 Reencauche de llantas usadas",
"2513 Fabricación de formas básicas de caucho",
"2519 Fabricación de otros productos de caucho n.c.p.",
"2521 Fabricación de formas básicas de plástico",
"2529 Fabricación de artículos de plástico n.c.p.",
"2610 Fabricación de vidrio y productos de vidrio",
"2691 Fabricación de productos de cerámica no refractaria, para uso no estructural",
"2692 Fabricación de productos de cerámica refractaria",
"2693 Fabricación de productos de arcilla y cerámica no refractarias, para uso estructural",
"2694 Fabricación de cemento, cal y yeso",
"2695 Fabricación de artículos de hormigón, cemento y yeso",
"2696 Corte, tallado y acabado de la piedra",
"2699 Fabricación de otros productos minerales no metálicos n.c.p.",
"2710 Industrias básicas de hierro y de acero",
"2721 Industrias básicas de metales preciosos",
"2729 Industrias básicas de otros metales no ferrosos",
"2731 Fundición de hierro y de acero",
"2732 Fundición de metales no ferrosos",
"2811 Fabricación de productos metálicos para uso estructural",
"2812 Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías",
"2813 Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central",
"2891 Forja, prensado, estampado y laminado de metal; pulvimetalurgia",
"2892 Tratamiento y revestimiento de metales",
"2893 Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería",
"2899 Fabricación de otros productos elaborados de metal n.c.p.",
"2911 Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas",
"2912 Fabricación de bombas, compresores, grifos y válvulas",
"2913 Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión",
"2914 Fabricación de hornos, hogares y quemadores industriales",
"2915 Fabricación de equipo de elevación y manipulación",
"2919 Fabricación de otros tipos de maquinaria de uso general n.c.p.",
"2921 Fabricación de maquinaria agropecuaria y forestal",
"2922 Fabricación de máquinas herramienta",
"2923 Fabricación de maquinaria para la metalurgia",
"2924 Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción",
"2925 Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco",
"2926 Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y artículos de cuero",
"2927 Fabricación de armas y municiones",
"2929 Fabricación de otros tipos de maquinaria de uso especial n.c.p.",
"2930 Fabricación de aparatos de uso doméstico n.c.p.",
"3000 Fabricación de maquinaria de oficina, contabilidad e informática",
"3110 Fabricación de motores, generadores y transformadores eléctricos",
"3120 Fabricación de aparatos de distribución y control de la energía eléctrica",
"3130 Fabricación de hilos y cables aislados",
"3140 Fabricación de acumuladores y de pilas eléctricas",
"3150 Fabricación de lámparas eléctricas y equipo de iluminación",
"3190 Fabricación de otros tipos de equipo eléctrico n.c.p.",
"3210 Fabricación de tubos y válvulas electrónicas y de otros componentes electrónicos",
"3220 Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía",
"3230 Fabricación de receptores de radio y televisión, de aparatos de grabación y de reproducción del sonido o de la imagen, y de productos conexos",
"3311 Fabricación de equipo médico y quirúrgico y de aparatos ortésicos y protésicos",
"3312 Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, excepto equipo de control de procesos industriales",
"3313 Fabricación de equipo de control de procesos industriales",
"3320 Fabricación de instrumentos ópticos y de equipo fotográfico",
"3330 Fabricación de relojes",
"3410 Fabricación de vehículos automotores y sus motores",
"3420 Fabricación de carrocerías para vehículos automotores",
"3430 Fabricación de partes, piezas (autopartes), accesorios (lujos) para vehículos automotores y para sus motores",
"3511 Construcción y reparación de buques",
"3512 Construcción y reparación de embarcaciones de recreo y de deporte",
"3520 Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías",
"3530 Fabricación de aeronaves y de naves espaciales",
"3591 Fabricación de motocicletas",
"3592 Fabricación de bicicletas y de sillones de ruedas para discapacitados",
"3599 Fabricación de otros tipos de equipo de transporte n.c.p.",
"3611 Fabricación de muebles para el hogar",
"3612 Fabricación de muebles para oficina",
"3613 Fabricación de muebles para comercio y servicios",
"3614 Fabricación de colchones y somieres",
"3619 Fabricación de otros muebles n.c.p.",
"3691 Fabricación de joyas y de artículos conexos",
"3692 Fabricación de instrumentos musicales",
"3693 Fabricación de artículos deportivos",
"3694 Fabricación de juegos y juguetes",
"3699 Otras industrias manufactureras n.c.p.",
"3710 Reciclaje de desperdicios y de desechos metálicos",
"3720 Reciclaje de desperdicios y de desechos no metálicos",
"4010 Generación, transmisión, distribución y comercialización de energía eléctrica",
"4020 Fabricación de gas, distribución de combustibles gaseosos por tuberías",
"4030 Suministro de vapor y agua caliente",
"4100 Captación, depuración y distribución de agua",
"4511 Trabajos de demolición y preparación de terrenos para la construcción de edificaciones",
"4512 Trabajos de demolición y preparación de terrenos para obras civiles",
"4521 Construcción de edificaciones para uso residencial",
"4522 Construcción de edificaciones para uso no residencial",
"4530 Construcción de obras de ingeniería civil",
"4541 Instalaciones hidráulicas y trabajos conexos",
"4542 Trabajos de electricidad",
"4543 Trabajos de instalación de equipos",
"4549 Otros trabajos de acondicionamiento",
"4551 Instalación de vidrios y ventanas",
"4552 Trabajos de pintura y terminación de muros y pisos",
"4559 Otros trabajos de terminación y acabado",
"4560 Alquiler de equipo para construcción y demolición dotado de operarios",
"5011 Comercio de vehículos automotores nuevos",
"5012 Comercio de vehículos automotores usados",
"5020 Mantenimiento y reparación de vehículos automotores",
"5030 Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores",
"5040 Comercio, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios",
"5051 Comercio al por menor de combustible para automotores",
"5052 Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores",
"5111 Comercio al por mayor a cambio de una retribución o por contrata de productos agrícolas (excepto café), silvícolas y de animales vivos y sus productos",
"5112 Comercio al por mayor a cambio de una retribución o por contrata de café pergamino",
"5113 Comercio al por mayor a cambio de una retribución o por contrata de productos manufacturados",
"5119 Comercio al por mayor a cambio de una retribución o por contrata de productos n.c.p.",
"5121 Comercio al por mayor de materias primas, productos agrícolas y pecuarios, excepto café y flores",
"5122 Comercio al por mayor de café pergamino",
"5123 Comercio al por mayor de flores y plantas ornamentales",
"5124 Comercio al por mayor de materias primas pecuarias y de animales vivos y sus productos",
"5125 Comercio al por mayor de productos alimenticios, excepto café trillado",
"5126 Comercio al por mayor de café trillado",
"5127 Comercio al por mayor de bebidas y productos del tabaco",
"5131 Comercio al por mayor de productos textiles y productos confeccionados para uso doméstico",
"5132 Comercio al por mayor de prendas de vestir, accesorios de prendas de vestir y artículos elaborados en piel",
"5133 Comercio al por mayor de calzado",
"5134 Comercio al por mayor de aparatos, artículos y equipo de uso doméstico",
"5135 Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador",
"5136 Comercio al por mayor de equipos médicos y quirúrgicos y de aparatos ortésicos y protésicos",
"5137 Comercio al por mayor de papel y cartón, productos de papel y cartón",
"5139 Comercio al por mayor de otros productos de consumo n.c.p.",
"5141 Comercio al por mayor de materiales de construcción, vidrio, artículos de ferretería y equipo y materiales de fontanería y calefacción",
"5142 Comercio al por mayor de pinturas y productos conexos",
"5151 Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y de productos conexos",
"5152 Comercio al por mayor de metales y minerales metalíferos",
"5153 Comercio al por mayor de productos químicos básicos, plásticos y caucho en formas primarias y productos químicos de uso agropecuario",
"5154 Comercio al por mayor de fibras textiles",
"5155 Comercio al por mayor de desperdicios o desechos industriales y material para reciclaje",
"5159 Comercio al por mayor de otros productos intermedios n.c.p.",
"5161 Comercio al por mayor de maquinaria y equipo para la agricultura, minería, construcción y la industria",
"5162 Comercio al por mayor de equipo de transporte, excepto vehículos automotores y motocicletas",
"5163 Comercio al por mayor de maquinaria y equipos de oficina",
"5164 Comercio al por mayor de computadores, equipo periférico y de programas de informática",
"5165 Comercio al por mayor de partes y equipos electrónicos y de comunicaciones",
"5169 Comercio al por mayor de maquinaria y equipo n.c.p.",
"5170 Mantenimiento y reparación de maquinaria y equipo",
"5190 Comercio al por mayor de productos diversos n.c.p.",
"5211 Comercio al por menor, en establecimientos no especializados, con surtido compuesto principalmente de alimentos (víveres en general), bebidas y tabaco",
"5219 Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco",
"5221 Comercio al por menor de frutas y verduras, en establecimientos especializados",
"5222 Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados",
"5223 Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados",
"5224 Comercio al por menor de productos de confitería, en establecimientos especializados",
"5225 Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados",
"5229 Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados",
"5231 Comercio al por menor de productos farmacéuticos, medicinales y odontológicos; artículos de perfumería, cosméticos y de tocador, en establecimientos especializados",
"5232 Comercio al por menor de productos textiles, en establecimientos especializados",
"5233 Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel), en establecimientos especializados",
"5234 Comercio al por menor de todo tipo de calzado, artículos de cuero y sucedáneos del cuero, en establecimientos especializados",
"5235 Comercio al por menor de electrodomésticos, en establecimientos especializados",
"5236 Comercio al por menor de muebles para el hogar, en establecimientos especializados",
"5237 Comercio al por menor de equipo y artículos de uso doméstico diferentes de electrodomésticos y muebles para el hogar, en establecimientos especializados",
"5239 Comercio al por menor de productos nuevos de consumo doméstico n.c.p., en establecimientos especializados",
"5241 Comercio al por menor de materiales de construcción, artículos de ferretería, cerrajería y productos de vidrio, excepto pinturas, en establecimientos especializados",
"5242 Comercio al por menor de pinturas, en establecimientos especializados",
"5243 Comercio al por menor de muebles para oficina, maquinaria y equipo de oficina, computadores y programas de computador, en establecimientos especializados",
"5244 Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados",
"5245 Comercio al por menor de equipo fotográfico, en establecimientos especializados",
"5246 Comercio al por menor de equipo óptico y de precisión, en establecimientos especializados",
"5249 Comercio al por menor de otros nuevos productos de consumo n.c.p., en establecimientos especializados",
"5251 Comercio al por menor de artículos usados, en establecimientos especializados",
"5252 Actividades de compraventa con pacto de retroventa",
"5261 Comercio al por menor a través de casas de venta por correo",
"5262 Comercio al por menor en puestos móviles",
"5269 Otros tipos de comercio al por menor no realizado en establecimientos",
"5271 Reparación de efectos personales",
"5272 Reparación de enseres domésticos",
"5511 Alojamiento en hoteles, hostales y apartahoteles",
"5512 Alojamiento en residencias, moteles y amoblados",
"5513 Alojamiento en centros vacacionales y zonas de camping",
"5519 Otros tipos de alojamiento n.c.p.",
"5521 Expendio a la mesa de comidas preparadas en restaurantes",
"5522 Expendio a la mesa de comidas preparadas en cafeterías",
"5523 Expendio por autoservicio de comidas preparadas en restaurantes",
"5524 Expendio por autoservicio de comidas preparadas en cafeterías",
"5525 Servicios de alimentación bajo contrato (catering)",
"5529 Otros tipos de expendio n.c.p. de alimentos preparados",
"5530 Expendio de bebidas alcohólicas para el consumo dentro del establecimiento",
"6010 Transporte por vía férrea",
"6021 Transporte urbano colectivo regular de pasajeros",
"6022 Transporte intermunicipal colectivo regular de pasajeros",
"6023 Transporte internacional colectivo regular de pasajeros",
"6031 Transporte no regular individual de pasajeros",
"6032 Transporte no regular colectivo de pasajeros",
"6039 Otros tipos de transporte no regular de pasajeros n.c.p",
"6041 Transporte municipal de carga por carretera",
"6042 Transporte intermunicipal de carga por carretera",
"6043 Transporte internacional de carga por carretera",
"6044 Alquiler de vehículos de carga con conductor",
"6050 Transporte por tuberías",
"6111 Transporte marítimo internacional",
"6112 Transporte marítimo de cabotaje",
"6120 Transporte fluvial",
"6211 Transporte regular nacional de pasajeros, por vía aérea",
"6212 Transporte regular nacional de carga, por vía aérea",
"6213 Transporte regular internacional de pasajeros, por vía aérea",
"6214 Transporte regular internacional de carga, por vía aérea",
"6220 Transporte no regular, por vía aérea",
"6310 Manipulación de carga",
"6320 Almacenamiento y depósito",
"6331 Actividades de estaciones, vías y servicios complementarios para el transporte terrestre",
"6332 Actividades de estaciones y servicios complementarios para el transporte acuático",
"6333 Actividades de aeropuertos y servicios complementarios para el transporte aéreo",
"6339 Otras actividades complementarias del transporte",
"6340 Actividades de agencias de viajes y organizadores de viajes, actividades de asistencia a turistas n.c.p",
"6390 Actividades de otros operadores logísticos",
"6411 Actividades postales nacionales",
"6412 Actividades de correo distintas de las actividades postales nacionales",
"6421 Servicios telefónicos y básicos",
"6422 Servicios de transmisión e intercambio de datos",
"6423 Servicios de transmisión de programas de radio y televisión",
"6424 Servicios de transmisión de radio y televisión por suscripción",
"6429 Otros servicios de telecomunicaciones n.c.p.",
"6511 Banca central",
"6512 Actividades de los bancos diferentes del banco central",
"6513 Actividades de las corporaciones financieras",
"6514 Actividades de las compañías de financiamiento comercial",
"6515 Actividades de las cooperativas financieras",
"6519 Otros tipos de intermediación monetaria n.c.p.",
"6591 Leasing financiero",
"6592 Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario",
"6593 Actividades de las sociedades de capitalización",
"6594 Actividades de compra de cartera o factoring",
"6595 Otros tipos de crédito",
"6596 Banca de segundo piso",
"6599 Otros tipos de intermediación financiera n.c.p.",
"6601 Planes de seguros generales",
"6602 Planes de seguros de vida",
"6603 Planes de reaseguros",
"6604 Planes de pensiones y cesantías",
"6711 Administración de mercados financieros",
"6712 Actividades de las bolsas de valores",
"6713 Actividades bursátiles",
"6714 Otras actividades relacionadas con el mercado de valores",
"6715 Actividades de las casas de cambio",
"6716 Actividades de los profesionales de compra y venta de divisas",
"6717 Actividades de las sociedades fiduciarias",
"6719 Actividades de servicios auxiliares de la intermediación financiera n.c.p.",
"6721 Actividades de servicios auxiliares del establecimiento y gestión de planes de seguros",
"6722 Actividades de servicios auxiliares de los fondos de pensiones y cesantías",
"7010 Actividades inmobiliarias realizadas con bienes propios o arrendados",
"7020 Actividades inmobiliarias realizadas a cambio de una retribución o por contrata",
"7111 Alquiler de equipo de transporte terrestre",
"7112 Alquiler de equipo de transporte acuático",
"7113 Alquiler de equipo de transporte aéreo",
"7121 Alquiler de maquinaria y equipo agropecuario y forestal",
"7122 Alquiler de maquinaria y equipo de construcción y de ingeniería civil",
"7123 Alquiler de maquinaria y equipo de oficina (incluso computadoras )",
"7129 Alquiler de otros tipos de maquinaria y equipo n.c.p.",
"7130 Alquiler de efectos personales y enseres domésticos n.c.p.",
"7210 Consultores en equipo de informática",
"7220 Consultores en programas de informática, elaboración y suministro de programas de informática",
"7230 Procesamiento de datos",
"7240 Actividades relacionadas con bases de datos y distribución en línea de contenidos electrónicos",
"7250 Mantenimiento y reparación de maquinaria de oficina, contabilidad e informática",
"7290 Otras actividades de informática",
"7310 Investigación y desarrollo experimental en el campo de las ciencias naturales, ciencias de la salud, ciencias agropecuarias y la ingeniería",
"7320 Investigación y desarrollo experimental en el campo de las ciencias sociales y las humanidades",
"7411 Actividades jurídicas",
"7412 Actividades de contabilidad, teneduría de libros y auditoria; asesoramiento en materia de impuestos",
"7413 Investigación de mercados y realización de encuestas de opinión publica",
"7414 Actividades de asesoramiento empresarial y en materia de gestión",
"7421 Actividades de arquitectura e ingeniería y actividades conexas de asesoramiento técnico",
"7422 Ensayos y análisis técnicos",
"7430 Publicidad",
"7491 Obtención y suministro de personal",
"7492 Actividades de investigación y seguridad",
"7493 Actividades de limpieza de edificios y de limpieza industrial",
"7494 Actividades de fotografía",
"7495 Actividades de envase y empaque",
"7499 Otras actividades empresariales n.c.p.",
"7511 Actividades legislativas de la administración pública",
"7512 Actividades ejecutivas de la administración pública",
"7513 Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social",
"7514 Actividades reguladoras y facilitadoras de la actividad económica",
"7515 Actividades auxiliares de servicios para la administración pública en general",
"7519 Otras actividades administrativas del Estado n.c.p.",
"7521 Relaciones exteriores",
"7522 Actividades de defensa",
"7523 Actividades de la justicia",
"7524 Actividades de la policía y protección civil",
"7530 Actividades de planes de seguridad social de afiliación obligatoria",
"8011 Educación preescolar",
"8012 Educación básica primaria",
"8021 Educación básica secundaria",
"8022 Educación media académica",
"8023 Educación media de formación técnica y profesional",
"8030 Educación superior",
"8090 Otros tipos de educación",
"8511 Actividades de las instituciones prestadoras de servicios de salud, con internación",
"8512 Actividades de la práctica médica",
"8513 Actividades de la práctica odontológica",
"8514 Actividades de apoyo diagnóstico",
"8515 Actividades de apoyo terapéutico",
"8519 Otras actividades relacionadas con la salud humana",
"8520 Actividades veterinarias",
"8531 Servicios sociales con alojamiento",
"8532 Servicios sociales sin alojamiento",
"9000 Eliminación de desperdicios y aguas residuales, saneamiento y actividades similares",
"9111 Actividades de organizaciones empresariales y de empleadores",
"9112 Actividades de organizaciones profesionales",
"9120 Actividades de sindicatos",
"9191 Actividades de organizaciones religiosas",
"9192 Actividades de organizaciones políticas",
"9199 Actividades de otras organizaciones n.c.p.",
"9211 Producción y distribución de filmes y videocintas",
"9212 Exhibición de filmes y videocintas",
"9213 Actividades de radio y televisión",
"9214 Actividades teatrales, musicales y otras actividades artísticas",
"9219 Otras actividades de entretenimiento n.c.p.",
"9220 Actividades de agencias de noticias",
"9231 Actividades de bibliotecas y archivos",
"9232 Actividades de museos y preservación de lugares y edificios históricos",
"9233 Actividades de jardines botánicos y zoológicos y de parques nacionales",
"9241 Actividades deportivas",
"9242 Actividades de juegos de azar",
"9249 Otras actividades de esparcimiento",
"9301 Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco",
"9302 Peluquería y otros tratamientos de belleza",
"9303 Pompas fúnebres y actividades conexas",
"9309 Otras actividades de servicios n.c.p.",
"9500 Actividades de hogares privados como empleadores de personal doméstico",
"9600 Actividades no diferenciadas de hogares privados como productores de bienes para uso propio",
"9700 Actividades no diferenciadas de hogares privados como productores de servicios para uso propio",
"9900 Organizaciones y órganos extraterritoriales"
];


export const municipios = [

"Abejorral-Antioquia",
"Abriaquí-Antioquia",
"Alejandría-Antioquia",
"Amagá-Antioquia",
"Dabeiba-Antioquia",
"Amalfi-Antioquia",
"Andes-Antioquia",
"Angelópolis-Antioquia",
"Angostura-Antioquia",
"Anorí-Antioquia",
"Santa Fé De Antioquia-Antioquia",
"Anzá-Antioquia",
"Apartadó-Antioquia",
"Arboletes-Antioquia",
"Argelia-Antioquia",
"Armenia-Antioquia",
"Barbosa-Antioquia",
"Belmira-Antioquia",
"Bello-Antioquia",
"Betania-Antioquia",
"Betulia-Antioquia",
"Ciudad Bolívar-Antioquia",
"Briceño-Antioquia",
"Buriticá-Antioquia",
"Cáceres-Antioquia",
"Caicedo-Antioquia",
"Caldas-Antioquia",
"Campamento-Antioquia",
"Cañasgordas-Antioquia",
"Caracolí-Antioquia",
"Caramanta-Antioquia",
"Carepa-Antioquia",
"El Carmen De Viboral-Antioquia",
"Carolina-Antioquia",
"Caucasia-Antioquia",
"Chigorodó-Antioquia",
"Cisneros-Antioquia",
"Cocorná-Antioquia",
"Concepción-Antioquia",
"Concordia-Antioquia",
"Copacabana-Antioquia",
"La Unión-Antioquia",
"Donmatías-Antioquia",
"Ebéjico-Antioquia",
"El Bagre-Antioquia",
"Entrerríos-Antioquia",
"Envigado-Antioquia",
"Fredonia-Antioquia",
"Frontino-Antioquia",
"Giraldo-Antioquia",
"Girardota-Antioquia",
"Gómez Plata-Antioquia",
"Granada-Antioquia",
"Guadalupe-Antioquia",
"Guarne-Antioquia",
"Guatapé-Antioquia",
"Heliconia-Antioquia",
"Hispania-Antioquia",
"Itagüí-Antioquia",
"Ituango-Antioquia",
"Jardín-Antioquia",
"Jericó-Antioquia",
"La Ceja-Antioquia",
"La Estrella-Antioquia",
"La Pintada-Antioquia",
"Liborina-Antioquia",
"Maceo-Antioquia",
"Marinilla-Antioquia",
"Montebello-Antioquia",
"Murindó-Antioquia",
"Mutatá-Antioquia",
"Nariño-Antioquia",
"Necoclí-Antioquia",
"Nechí-Antioquia",
"Olaya-Antioquia",
"Peñol-Antioquia",
"Peque-Antioquia",
"Pueblorrico-Antioquia",
"Puerto Berrío-Antioquia",
"Puerto Nare-Antioquia",
"Puerto Triunfo-Antioquia",
"Remedios-Antioquia",
"Retiro-Antioquia",
"Rionegro-Antioquia",
"Sabanalarga-Antioquia",
"Sabaneta-Antioquia",
"Salgar-Antioquia",
"San Andrés De Cuerquía-Antioquia",
"San Carlos-Antioquia",
"San Francisco-Antioquia",
"San Jerónimo-Antioquia",
"San José De La Montaña-Antioquia",
"San Juan De Urabá-Antioquia",
"San Luis-Antioquia",
"San Pedro De Los Milagros-Antioquia",
"San Pedro De Urabá-Antioquia",
"San Rafael-Antioquia",
"San Roque-Antioquia",
"San Vicente Ferrer-Antioquia",
"Santa Bárbara-Antioquia",
"Santa Rosa De Osos-Antioquia",
"Santo Domingo-Antioquia",
"El Santuario-Antioquia",
"Segovia-Antioquia",
"Sonsón-Antioquia",
"Sopetrán-Antioquia",
"Támesis-Antioquia",
"Tarazá-Antioquia",
"Tarso-Antioquia",
"Titiribí-Antioquia",
"Toledo-Antioquia",
"Turbo-Antioquia",
"Uramita-Antioquia",
"Urrao-Antioquia",
"Valdivia-Antioquia",
"Valparaíso-Antioquia",
"Vegachí-Antioquia",
"Venecia-Antioquia",
"Vigía Del Fuerte-Antioquia",
"Yarumal-Antioquia",
"Yalí-Antioquia",
"Yolombó-Antioquia",
"Yondó-Antioquia",
"Zaragoza-Antioquia",
"Barranquilla-Atlántico",
"Baranoa-Atlántico",
"Campo De La Cruz-Atlántico",
"Candelaria-Atlántico",
"Galapa-Atlántico",
"Juan De Acosta-Atlántico",
"Luruaco-Atlántico",
"Malambo-Atlántico",
"Manatí-Atlántico",
"Palmar De Varela-Atlántico",
"Piojó-Atlántico",
"Polonuevo-Atlántico",
"Ponedera-Atlántico",
"Puerto Colombia-Atlántico",
"Repelón-Atlántico",
"Sabanagrande-Atlántico",
"Sabanalarga-Atlántico",
"Santa Lucía-Atlántico",
"Santo Tomás-Atlántico",
"Soledad-Atlántico",
"Suan-Atlántico",
"Tubará-Atlántico",
"Usiacurí-Atlántico",
"Bogotá, D.C.-Bogotá, D.C.",
"Cartagena De Indias-Bolívar",
"Achí-Bolívar",
"Altos Del Rosario-Bolívar",
"Arenal-Bolívar",
"Arjona-Bolívar",
"Arroyohondo-Bolívar",
"Barranco De Loba-Bolívar",
"Calamar-Bolívar",
"Cantagallo-Bolívar",
"Cicuco-Bolívar",
"Córdoba-Bolívar",
"Clemencia-Bolívar",
"El Carmen De Bolívar-Bolívar",
"El Guamo-Bolívar",
"El Peñón-Bolívar",
"Hatillo De Loba-Bolívar",
"Magangué-Bolívar",
"Mahates-Bolívar",
"Margarita-Bolívar",
"María La Baja-Bolívar",
"Montecristo-Bolívar",
"Mompós-Bolívar",
"Morales-Bolívar",
"Norosí-Bolívar",
"Pinillos-Bolívar",
"Regidor-Bolívar",
"Río Viejo-Bolívar",
"San Cristóbal-Bolívar",
"San Estanislao-Bolívar",
"San Fernando-Bolívar",
"San Jacinto-Bolívar",
"San Jacinto Del Cauca-Bolívar",
"San Juan Nepomuceno-Bolívar",
"San Martín De Loba-Bolívar",
"San Pablo-Bolívar",
"Santa Catalina-Bolívar",
"Santa Rosa-Bolívar",
"Santa Rosa Del Sur-Bolívar",
"Simití-Bolívar",
"Soplaviento-Bolívar",
"Talaigua Nuevo-Bolívar",
"Tiquisio-Bolívar",
"Turbaco-Bolívar",
"Turbaná-Bolívar",
"Villanueva-Bolívar",
"Zambrano-Bolívar",
"Tunja-Boyacá",
"Almeida-Boyacá",
"Aquitania-Boyacá",
"Arcabuco-Boyacá",
"Belén-Boyacá",
"Berbeo-Boyacá",
"Betéitiva-Boyacá",
"Boavita-Boyacá",
"Boyacá-Boyacá",
"Briceño-Boyacá",
"Buenavista-Boyacá",
"Busbanzá-Boyacá",
"Caldas-Boyacá",
"Campohermoso-Boyacá",
"Cerinza-Boyacá",
"Chinavita-Boyacá",
"Chiquinquirá-Boyacá",
"Chiscas-Boyacá",
"Chita-Boyacá",
"Chitaraque-Boyacá",
"Chivatá-Boyacá",
"Ciénega-Boyacá",
"Cómbita-Boyacá",
"Coper-Boyacá",
"Corrales-Boyacá",
"Covarachía-Boyacá",
"Cubará-Boyacá",
"Cucaita-Boyacá",
"Cuítiva-Boyacá",
"Chíquiza-Boyacá",
"Chivor-Boyacá",
"Duitama-Boyacá",
"El Cocuy-Boyacá",
"El Espino-Boyacá",
"Firavitoba-Boyacá",
"Floresta-Boyacá",
"Gachantivá-Boyacá",
"Gámeza-Boyacá",
"Garagoa-Boyacá",
"Guacamayas-Boyacá",
"Guateque-Boyacá",
"Guayatá-Boyacá",
"Güicán De La Sierra-Boyacá",
"Iza-Boyacá",
"Jenesano-Boyacá",
"Jericó-Boyacá",
"Labranzagrande-Boyacá",
"La Capilla-Boyacá",
"La Victoria-Boyacá",
"La Uvita-Boyacá",
"Villa De Leyva-Boyacá",
"Macanal-Boyacá",
"Maripí-Boyacá",
"Miraflores-Boyacá",
"Mongua-Boyacá",
"Monguí-Boyacá",
"Moniquirá-Boyacá",
"Motavita-Boyacá",
"Muzo-Boyacá",
"Nobsa-Boyacá",
"Nuevo Colón-Boyacá",
"Oicatá-Boyacá",
"Otanche-Boyacá",
"Pachavita-Boyacá",
"Páez-Boyacá",
"Paipa-Boyacá",
"Pajarito-Boyacá",
"Panqueba-Boyacá",
"Pauna-Boyacá",
"Paya-Boyacá",
"Paz De Río-Boyacá",
"Pesca-Boyacá",
"Pisba-Boyacá",
"Puerto Boyacá-Boyacá",
"Quípama-Boyacá",
"Ramiriquí-Boyacá",
"Ráquira-Boyacá",
"Rondón-Boyacá",
"Saboyá-Boyacá",
"Sáchica-Boyacá",
"Samacá-Boyacá",
"San Eduardo-Boyacá",
"San José De Pare-Boyacá",
"San Luis De Gaceno-Boyacá",
"San Mateo-Boyacá",
"San Miguel De Sema-Boyacá",
"San Pablo De Borbur-Boyacá",
"Santana-Boyacá",
"Santa María-Boyacá",
"Santa Rosa De Viterbo-Boyacá",
"Santa Sofía-Boyacá",
"Sativanorte-Boyacá",
"Sativasur-Boyacá",
"Siachoque-Boyacá",
"Soatá-Boyacá",
"Socotá-Boyacá",
"Socha-Boyacá",
"Sogamoso-Boyacá",
"Somondoco-Boyacá",
"Sora-Boyacá",
"Sotaquirá-Boyacá",
"Soracá-Boyacá",
"Susacón-Boyacá",
"Sutamarchán-Boyacá",
"Sutatenza-Boyacá",
"Tasco-Boyacá",
"Tenza-Boyacá",
"Tibaná-Boyacá",
"Tibasosa-Boyacá",
"Tinjacá-Boyacá",
"Tipacoque-Boyacá",
"Toca-Boyacá",
"Togüí-Boyacá",
"Tópaga-Boyacá",
"Tota-Boyacá",
"Tununguá-Boyacá",
"Turmequé-Boyacá",
"Tuta-Boyacá",
"Tutazá-Boyacá",
"Úmbita-Boyacá",
"Ventaquemada-Boyacá",
"Viracachá-Boyacá",
"Zetaquira-Boyacá",
"Manizales-Caldas",
"Aguadas-Caldas",
"Anserma-Caldas",
"Aranzazu-Caldas",
"Belalcázar-Caldas",
"Chinchiná-Caldas",
"Filadelfia-Caldas",
"La Dorada-Caldas",
"La Merced-Caldas",
"Manzanares-Caldas",
"Marmato-Caldas",
"Marquetalia-Caldas",
"Marulanda-Caldas",
"Neira-Caldas",
"Norcasia-Caldas",
"Pácora-Caldas",
"Palestina-Caldas",
"Pensilvania-Caldas",
"Riosucio-Caldas",
"Risaralda-Caldas",
"Salamina-Caldas",
"Samaná-Caldas",
"San José-Caldas",
"Supía-Caldas",
"Victoria-Caldas",
"Villamaría-Caldas",
"Viterbo-Caldas",
"Florencia-Caquetá",
"Albania-Caquetá",
"Belén De Los Andaquíes-Caquetá",
"Cartagena Del Chairá-Caquetá",
"Curillo-Caquetá",
"El Doncello-Caquetá",
"El Paujíl-Caquetá",
"La Montañita-Caquetá",
"Milán-Caquetá",
"Morelia-Caquetá",
"Puerto Rico-Caquetá",
"San José Del Fragua-Caquetá",
"San Vicente Del Caguán-Caquetá",
"Solano-Caquetá",
"Solita-Caquetá",
"Valparaíso-Caquetá",
"Popayán-Cauca",
"Almaguer-Cauca",
"Argelia-Cauca",
"Balboa-Cauca",
"Bolívar-Cauca",
"Buenos Aires-Cauca",
"Cajibío-Cauca",
"Caldono-Cauca",
"Caloto-Cauca",
"Corinto-Cauca",
"El Tambo-Cauca",
"Florencia-Cauca",
"Guachené-Cauca",
"Guapi-Cauca",
"Inzá-Cauca",
"Jambaló-Cauca",
"La Sierra-Cauca",
"La Vega-Cauca",
"López De Micay-Cauca",
"Mercaderes-Cauca",
"Miranda-Cauca",
"Morales-Cauca",
"Padilla-Cauca",
"Páez-Cauca",
"Patía-Cauca",
"Piamonte-Cauca",
"Piendamó - Tunía-Cauca",
"Puerto Tejada-Cauca",
"Puracé-Cauca",
"Rosas-Cauca",
"San Sebastián-Cauca",
"Santander De Quilichao-Cauca",
"Santa Rosa-Cauca",
"Silvia-Cauca",
"Sotará - Paispamba-Cauca",
"Suárez-Cauca",
"Sucre-Cauca",
"Timbío-Cauca",
"Timbiquí-Cauca",
"Toribío-Cauca",
"Totoró-Cauca",
"Villa Rica-Cauca",
"Valledupar-Cesar",
"Aguachica-Cesar",
"Agustín Codazzi-Cesar",
"Astrea-Cesar",
"Becerril-Cesar",
"Bosconia-Cesar",
"Chimichagua-Cesar",
"Chiriguaná-Cesar",
"Curumaní-Cesar",
"El Copey-Cesar",
"El Paso-Cesar",
"Gamarra-Cesar",
"González-Cesar",
"La Gloria-Cesar",
"La Jagua De Ibirico-Cesar",
"Manaure Balcón Del Cesar-Cesar",
"Pailitas-Cesar",
"Pelaya-Cesar",
"Pueblo Bello-Cesar",
"Río De Oro-Cesar",
"La Paz-Cesar",
"San Alberto-Cesar",
"San Diego-Cesar",
"San Martín-Cesar",
"Tamalameque-Cesar",
"Montería-Córdoba",
"Ayapel-Córdoba",
"Buenavista-Córdoba",
"Canalete-Córdoba",
"Cereté-Córdoba",
"Chimá-Córdoba",
"Chinú-Córdoba",
"Ciénaga De Oro-Córdoba",
"Cotorra-Córdoba",
"La Apartada-Córdoba",
"Lorica-Córdoba",
"Los Córdobas-Córdoba",
"Momil-Córdoba",
"Montelíbano-Córdoba",
"Moñitos-Córdoba",
"Planeta Rica-Córdoba",
"Pueblo Nuevo-Córdoba",
"Puerto Escondido-Córdoba",
"Puerto Libertador-Córdoba",
"Purísima De La Concepción-Córdoba",
"Sahagún-Córdoba",
"San Andrés De Sotavento-Córdoba",
"San Antero-Córdoba",
"San Bernardo Del Viento-Córdoba",
"San Carlos-Córdoba",
"San José De Uré-Córdoba",
"San Pelayo-Córdoba",
"Tierralta-Córdoba",
"Tuchín-Córdoba",
"Valencia-Córdoba",
"Agua De Dios-Cundinamarca",
"Albán-Cundinamarca",
"Anapoima-Cundinamarca",
"Anolaima-Cundinamarca",
"Arbeláez-Cundinamarca",
"Beltrán-Cundinamarca",
"Bituima-Cundinamarca",
"Bojacá-Cundinamarca",
"Cabrera-Cundinamarca",
"Cachipay-Cundinamarca",
"Cajicá-Cundinamarca",
"Caparrapí-Cundinamarca",
"Cáqueza-Cundinamarca",
"Carmen De Carupa-Cundinamarca",
"Chaguaní-Cundinamarca",
"Chía-Cundinamarca",
"Chipaque-Cundinamarca",
"Choachí-Cundinamarca",
"Chocontá-Cundinamarca",
"Cogua-Cundinamarca",
"Cota-Cundinamarca",
"Cucunubá-Cundinamarca",
"El Colegio-Cundinamarca",
"El Peñón-Cundinamarca",
"El Rosal-Cundinamarca",
"Facatativá-Cundinamarca",
"Fómeque-Cundinamarca",
"Fosca-Cundinamarca",
"Funza-Cundinamarca",
"Fúquene-Cundinamarca",
"Fusagasugá-Cundinamarca",
"Gachalá-Cundinamarca",
"Gachancipá-Cundinamarca",
"Gachetá-Cundinamarca",
"Gama-Cundinamarca",
"Girardot-Cundinamarca",
"Granada-Cundinamarca",
"Guachetá-Cundinamarca",
"Guaduas-Cundinamarca",
"Guasca-Cundinamarca",
"Guataquí-Cundinamarca",
"Guatavita-Cundinamarca",
"Guayabal De Síquima-Cundinamarca",
"Guayabetal-Cundinamarca",
"Gutiérrez-Cundinamarca",
"Jerusalén-Cundinamarca",
"Junín-Cundinamarca",
"La Calera-Cundinamarca",
"La Mesa-Cundinamarca",
"La Palma-Cundinamarca",
"La Peña-Cundinamarca",
"La Vega-Cundinamarca",
"Lenguazaque-Cundinamarca",
"Machetá-Cundinamarca",
"Madrid-Cundinamarca",
"Manta-Cundinamarca",
"Medina-Cundinamarca",
"Mosquera-Cundinamarca",
"Nariño-Cundinamarca",
"Nemocón-Cundinamarca",
"Nilo-Cundinamarca",
"Nimaima-Cundinamarca",
"Nocaima-Cundinamarca",
"Venecia-Cundinamarca",
"Pacho-Cundinamarca",
"Paime-Cundinamarca",
"Pandi-Cundinamarca",
"Paratebueno-Cundinamarca",
"Pasca-Cundinamarca",
"Puerto Salgar-Cundinamarca",
"Pulí-Cundinamarca",
"Quebradanegra-Cundinamarca",
"Quetame-Cundinamarca",
"Quipile-Cundinamarca",
"Apulo-Cundinamarca",
"Ricaurte-Cundinamarca",
"San Antonio Del Tequendama-Cundinamarca",
"San Bernardo-Cundinamarca",
"San Cayetano-Cundinamarca",
"San Francisco-Cundinamarca",
"San Juan De Rioseco-Cundinamarca",
"Sasaima-Cundinamarca",
"Sesquilé-Cundinamarca",
"Sibaté-Cundinamarca",
"Silvania-Cundinamarca",
"Simijaca-Cundinamarca",
"Soacha-Cundinamarca",
"Sopó-Cundinamarca",
"Subachoque-Cundinamarca",
"Suesca-Cundinamarca",
"Supatá-Cundinamarca",
"Susa-Cundinamarca",
"Sutatausa-Cundinamarca",
"Tabio-Cundinamarca",
"Tausa-Cundinamarca",
"Tena-Cundinamarca",
"Tenjo-Cundinamarca",
"Tibacuy-Cundinamarca",
"Tibirita-Cundinamarca",
"Tocaima-Cundinamarca",
"Tocancipá-Cundinamarca",
"Topaipí-Cundinamarca",
"Ubalá-Cundinamarca",
"Ubaque-Cundinamarca",
"Villa De San Diego De Ubaté-Cundinamarca",
"Une-Cundinamarca",
"Útica-Cundinamarca",
"Vergara-Cundinamarca",
"Vianí-Cundinamarca",
"Villagómez-Cundinamarca",
"Villapinzón-Cundinamarca",
"Villeta-Cundinamarca",
"Viotá-Cundinamarca",
"Yacopí-Cundinamarca",
"Zipacón-Cundinamarca",
"Zipaquirá-Cundinamarca",
"Quibdó-Chocó",
"Acandí-Chocó",
"Alto Baudó-Chocó",
"Atrato-Chocó",
"Bagadó-Chocó",
"Bahía Solano-Chocó",
"Bajo Baudó-Chocó",
"Bojayá-Chocó",
"El Cantón Del San Pablo-Chocó",
"Carmen Del Darién-Chocó",
"Cértegui-Chocó",
"Condoto-Chocó",
"El Carmen De Atrato-Chocó",
"El Litoral Del San Juan-Chocó",
"Istmina-Chocó",
"Juradó-Chocó",
"Lloró-Chocó",
"Medio Atrato-Chocó",
"Medio Baudó-Chocó",
"Medio San Juan-Chocó",
"Nóvita-Chocó",
"Nuquí-Chocó",
"Río Iró-Chocó",
"Río Quito-Chocó",
"Riosucio-Chocó",
"San José Del Palmar-Chocó",
"Sipí-Chocó",
"Tadó-Chocó",
"Unguía-Chocó",
"Unión Panamericana-Chocó",
"Neiva-Huila",
"Acevedo-Huila",
"Agrado-Huila",
"Aipe-Huila",
"Algeciras-Huila",
"Altamira-Huila",
"Baraya-Huila",
"Campoalegre-Huila",
"Colombia-Huila",
"Elías-Huila",
"Garzón-Huila",
"Gigante-Huila",
"Guadalupe-Huila",
"Hobo-Huila",
"Íquira-Huila",
"Isnos-Huila",
"La Argentina-Huila",
"La Plata-Huila",
"Nátaga-Huila",
"Oporapa-Huila",
"Paicol-Huila",
"Palermo-Huila",
"Palestina-Huila",
"Pital-Huila",
"Pitalito-Huila",
"Rivera-Huila",
"Saladoblanco-Huila",
"San Agustín-Huila",
"Santa María-Huila",
"Suaza-Huila",
"Tarqui-Huila",
"Tesalia-Huila",
"Tello-Huila",
"Teruel-Huila",
"Timaná-Huila",
"Villavieja-Huila",
"Yaguará-Huila",
"Riohacha-La Guajira",
"Albania-La Guajira",
"Barrancas-La Guajira",
"Dibulla-La Guajira",
"Distracción-La Guajira",
"El Molino-La Guajira",
"Fonseca-La Guajira",
"Hatonuevo-La Guajira",
"La Jagua Del Pilar-La Guajira",
"Maicao-La Guajira",
"Manaure-La Guajira",
"San Juan Del Cesar-La Guajira",
"Uribia-La Guajira",
"Urumita-La Guajira",
"Villanueva-La Guajira",
"Santa Marta-Magdalena",
"Algarrobo-Magdalena",
"Aracataca-Magdalena",
"Ariguaní-Magdalena",
"Cerro De San Antonio-Magdalena",
"Chivolo-Magdalena",
"Ciénaga-Magdalena",
"Concordia-Magdalena",
"El Banco-Magdalena",
"El Piñón-Magdalena",
"El Retén-Magdalena",
"Fundación-Magdalena",
"Guamal-Magdalena",
"Nueva Granada-Magdalena",
"Pedraza-Magdalena",
"Pijiño Del Carmen-Magdalena",
"Pivijay-Magdalena",
"Plato-Magdalena",
"Puebloviejo-Magdalena",
"Remolino-Magdalena",
"Sabanas De San Ángel-Magdalena",
"Salamina-Magdalena",
"San Sebastián De Buenavista-Magdalena",
"San Zenón-Magdalena",
"Santa Ana-Magdalena",
"Santa Bárbara De Pinto-Magdalena",
"Sitionuevo-Magdalena",
"Tenerife-Magdalena",
"Zapayán-Magdalena",
"Zona Bananera-Magdalena",
"Villavicencio-Meta",
"Acacías-Meta",
"Barranca De Upía-Meta",
"Cabuyaro-Meta",
"Castilla La Nueva-Meta",
"Cubarral-Meta",
"Cumaral-Meta",
"El Calvario-Meta",
"El Castillo-Meta",
"El Dorado-Meta",
"Fuente De Oro-Meta",
"Granada-Meta",
"Guamal-Meta",
"Mapiripán-Meta",
"Mesetas-Meta",
"La Macarena-Meta",
"Uribe-Meta",
"Lejanías-Meta",
"Puerto Concordia-Meta",
"Puerto Gaitán-Meta",
"Puerto López-Meta",
"Puerto Lleras-Meta",
"Puerto Rico-Meta",
"Restrepo-Meta",
"San Carlos De Guaroa-Meta",
"San Juan De Arama-Meta",
"San Juanito-Meta",
"San Martín-Meta",
"Vistahermosa-Meta",
"Pasto-Nariño",
"Albán-Nariño",
"Aldana-Nariño",
"Ancuya-Nariño",
"Arboleda-Nariño",
"Barbacoas-Nariño",
"Belén-Nariño",
"Buesaco-Nariño",
"Colón-Nariño",
"Consacá-Nariño",
"Contadero-Nariño",
"Córdoba-Nariño",
"Cuaspud Carlosama-Nariño",
"Cumbal-Nariño",
"Cumbitara-Nariño",
"Chachagüí-Nariño",
"El Charco-Nariño",
"El Peñol-Nariño",
"El Rosario-Nariño",
"El Tablón De Gómez-Nariño",
"El Tambo-Nariño",
"Funes-Nariño",
"Guachucal-Nariño",
"Guaitarilla-Nariño",
"Gualmatán-Nariño",
"Iles-Nariño",
"Imués-Nariño",
"Ipiales-Nariño",
"La Cruz-Nariño",
"La Florida-Nariño",
"La Llanada-Nariño",
"La Tola-Nariño",
"La Unión-Nariño",
"Leiva-Nariño",
"Linares-Nariño",
"Los Andes-Nariño",
"Magüí-Nariño",
"Mallama-Nariño",
"Mosquera-Nariño",
"Nariño-Nariño",
"Olaya Herrera-Nariño",
"Ospina-Nariño",
"Francisco Pizarro-Nariño",
"Policarpa-Nariño",
"Potosí-Nariño",
"Providencia-Nariño",
"Puerres-Nariño",
"Pupiales-Nariño",
"Ricaurte-Nariño",
"Roberto Payán-Nariño",
"Samaniego-Nariño",
"Sandoná-Nariño",
"San Bernardo-Nariño",
"San Lorenzo-Nariño",
"San Pablo-Nariño",
"San Pedro De Cartago-Nariño",
"Santa Bárbara-Nariño",
"Santacruz-Nariño",
"Sapuyes-Nariño",
"Taminango-Nariño",
"Tangua-Nariño",
"San Andrés De Tumaco-Nariño",
"Túquerres-Nariño",
"Yacuanquer-Nariño",
"San José De Cúcuta-Norte de Santander",
"Ábrego-Norte de Santander",
"Arboledas-Norte de Santander",
"Bochalema-Norte de Santander",
"Bucarasica-Norte de Santander",
"Cácota-Norte de Santander",
"Cáchira-Norte de Santander",
"Chinácota-Norte de Santander",
"Chitagá-Norte de Santander",
"Convención-Norte de Santander",
"Cucutilla-Norte de Santander",
"Durania-Norte de Santander",
"El Carmen-Norte de Santander",
"El Tarra-Norte de Santander",
"El Zulia-Norte de Santander",
"Gramalote-Norte de Santander",
"Hacarí-Norte de Santander",
"Herrán-Norte de Santander",
"Labateca-Norte de Santander",
"La Esperanza-Norte de Santander",
"La Playa-Norte de Santander",
"Los Patios-Norte de Santander",
"Lourdes-Norte de Santander",
"Mutiscua-Norte de Santander",
"Ocaña-Norte de Santander",
"Pamplona-Norte de Santander",
"Pamplonita-Norte de Santander",
"Puerto Santander-Norte de Santander",
"Ragonvalia-Norte de Santander",
"Salazar-Norte de Santander",
"San Calixto-Norte de Santander",
"San Cayetano-Norte de Santander",
"Santiago-Norte de Santander",
"Sardinata-Norte de Santander",
"Silos-Norte de Santander",
"Teorama-Norte de Santander",
"Tibú-Norte de Santander",
"Toledo-Norte de Santander",
"Villa Caro-Norte de Santander",
"Villa Del Rosario-Norte de Santander",
"Armenia-Quindio",
"Buenavista-Quindio",
"Calarcá-Quindio",
"Circasia-Quindio",
"Córdoba-Quindio",
"Filandia-Quindio",
"Génova-Quindio",
"La Tebaida-Quindio",
"Montenegro-Quindio",
"Pijao-Quindio",
"Quimbaya-Quindio",
"Salento-Quindio",
"Pereira-Risaralda",
"Apía-Risaralda",
"Balboa-Risaralda",
"Belén De Umbría-Risaralda",
"Dosquebradas-Risaralda",
"Guática-Risaralda",
"La Celia-Risaralda",
"La Virginia-Risaralda",
"Marsella-Risaralda",
"Mistrató-Risaralda",
"Pueblo Rico-Risaralda",
"Quinchía-Risaralda",
"Santa Rosa De Cabal-Risaralda",
"Santuario-Risaralda",
"Bucaramanga-Santander",
"Aguada-Santander",
"Albania-Santander",
"Aratoca-Santander",
"Barbosa-Santander",
"Barichara-Santander",
"Barrancabermeja-Santander",
"Betulia-Santander",
"Bolívar-Santander",
"Cabrera-Santander",
"California-Santander",
"Capitanejo-Santander",
"Carcasí-Santander",
"Cepitá-Santander",
"Cerrito-Santander",
"Charalá-Santander",
"Charta-Santander",
"Chima-Santander",
"Chipatá-Santander",
"Cimitarra-Santander",
"Concepción-Santander",
"Confines-Santander",
"Contratación-Santander",
"Coromoro-Santander",
"Curití-Santander",
"El Carmen De Chucuri-Santander",
"El Guacamayo-Santander",
"El Peñón-Santander",
"El Playón-Santander",
"Encino-Santander",
"Enciso-Santander",
"Florián-Santander",
"Floridablanca-Santander",
"Galán-Santander",
"Gámbita-Santander",
"Girón-Santander",
"Guaca-Santander",
"Guadalupe-Santander",
"Guapotá-Santander",
"Guavatá-Santander",
"Güepsa-Santander",
"Hato-Santander",
"Jesús María-Santander",
"Jordán-Santander",
"La Belleza-Santander",
"Landázuri-Santander",
"La Paz-Santander",
"Lebrija-Santander",
"Los Santos-Santander",
"Macaravita-Santander",
"Málaga-Santander",
"Matanza-Santander",
"Mogotes-Santander",
"Molagavita-Santander",
"Ocamonte-Santander",
"Oiba-Santander",
"Onzaga-Santander",
"Palmar-Santander",
"Palmas Del Socorro-Santander",
"Páramo-Santander",
"Piedecuesta-Santander",
"Pinchote-Santander",
"Puente Nacional-Santander",
"Puerto Parra-Santander",
"Puerto Wilches-Santander",
"Rionegro-Santander",
"Sabana De Torres-Santander",
"San Andrés-Santander",
"San Benito-Santander",
"San Gil-Santander",
"San Joaquín-Santander",
"San José De Miranda-Santander",
"San Miguel-Santander",
"San Vicente De Chucurí-Santander",
"Santa Bárbara-Santander",
"Santa Helena Del Opón-Santander",
"Simacota-Santander",
"Socorro-Santander",
"Suaita-Santander",
"Sucre-Santander",
"Suratá-Santander",
"Tona-Santander",
"Valle De San José-Santander",
"Vélez-Santander",
"Vetas-Santander",
"Villanueva-Santander",
"Zapatoca-Santander",
"Sincelejo-Sucre",
"Buenavista-Sucre",
"Caimito-Sucre",
"Colosó-Sucre",
"Corozal-Sucre",
"Coveñas-Sucre",
"Chalán-Sucre",
"El Roble-Sucre",
"Galeras-Sucre",
"Guaranda-Sucre",
"La Unión-Sucre",
"Los Palmitos-Sucre",
"Majagual-Sucre",
"Morroa-Sucre",
"Ovejas-Sucre",
"Palmito-Sucre",
"Sampués-Sucre",
"San Benito Abad-Sucre",
"San Juan De Betulia-Sucre",
"San Marcos-Sucre",
"San Onofre-Sucre",
"San Pedro-Sucre",
"San Luis De Sincé-Sucre",
"Sucre-Sucre",
"Santiago De Tolú-Sucre",
"San José De Toluviejo-Sucre",
"Ibagué-Tolima",
"Alpujarra-Tolima",
"Alvarado-Tolima",
"Ambalema-Tolima",
"Anzoátegui-Tolima",
"Armero-Tolima",
"Ataco-Tolima",
"Cajamarca-Tolima",
"Carmen De Apicalá-Tolima",
"Casabianca-Tolima",
"Chaparral-Tolima",
"Coello-Tolima",
"Coyaima-Tolima",
"Cunday-Tolima",
"Dolores-Tolima",
"Espinal-Tolima",
"Falan-Tolima",
"Flandes-Tolima",
"Fresno-Tolima",
"Guamo-Tolima",
"Herveo-Tolima",
"Honda-Tolima",
"Icononzo-Tolima",
"Lérida-Tolima",
"Líbano-Tolima",
"San Sebastián De Mariquita-Tolima",
"Melgar-Tolima",
"Murillo-Tolima",
"Natagaima-Tolima",
"Ortega-Tolima",
"Palocabildo-Tolima",
"Piedras-Tolima",
"Planadas-Tolima",
"Prado-Tolima",
"Purificación-Tolima",
"Rioblanco-Tolima",
"Roncesvalles-Tolima",
"Rovira-Tolima",
"Saldaña-Tolima",
"San Antonio-Tolima",
"San Luis-Tolima",
"Santa Isabel-Tolima",
"Suárez-Tolima",
"Valle De San Juan-Tolima",
"Venadillo-Tolima",
"Villahermosa-Tolima",
"Villarrica-Tolima",
"Cali-Valle del Cauca",
"Alcalá-Valle del Cauca",
"Andalucía-Valle del Cauca",
"Ansermanuevo-Valle del Cauca",
"Argelia-Valle del Cauca",
"Bolívar-Valle del Cauca",
"Buenaventura-Valle del Cauca",
"Guadalajara De Buga-Valle del Cauca",
"Bugalagrande-Valle del Cauca",
"Caicedonia-Valle del Cauca",
"Calima-Valle del Cauca",
"Candelaria-Valle del Cauca",
"Cartago-Valle del Cauca",
"Dagua-Valle del Cauca",
"El Águila-Valle del Cauca",
"El Cairo-Valle del Cauca",
"El Cerrito-Valle del Cauca",
"El Dovio-Valle del Cauca",
"Florida-Valle del Cauca",
"Ginebra-Valle del Cauca",
"Guacarí-Valle del Cauca",
"Jamundí-Valle del Cauca",
"La Cumbre-Valle del Cauca",
"La Unión-Valle del Cauca",
"La Victoria-Valle del Cauca",
"Obando-Valle del Cauca",
"Palmira-Valle del Cauca",
"Pradera-Valle del Cauca",
"Restrepo-Valle del Cauca",
"Riofrío-Valle del Cauca",
"Roldanillo-Valle del Cauca",
"San Pedro-Valle del Cauca",
"Sevilla-Valle del Cauca",
"Toro-Valle del Cauca",
"Trujillo-Valle del Cauca",
"Tuluá-Valle del Cauca",
"Ulloa-Valle del Cauca",
"Versalles-Valle del Cauca",
"Vijes-Valle del Cauca",
"Yotoco-Valle del Cauca",
"Yumbo-Valle del Cauca",
"Zarzal-Valle del Cauca",
"Arauca-Arauca",
"Arauquita-Arauca",
"Cravo Norte-Arauca",
"Fortul-Arauca",
"Puerto Rondón-Arauca",
"Saravena-Arauca",
"Tame-Arauca",
"Yopal-Casanare",
"Aguazul-Casanare",
"Chámeza-Casanare",
"Hato Corozal-Casanare",
"La Salina-Casanare",
"Maní-Casanare",
"Monterrey-Casanare",
"Nunchía-Casanare",
"Orocué-Casanare",
"Paz De Ariporo-Casanare",
"Pore-Casanare",
"Recetor-Casanare",
"Sabanalarga-Casanare",
"Sácama-Casanare",
"San Luis De Palenque-Casanare",
"Támara-Casanare",
"Tauramena-Casanare",
"Trinidad-Casanare",
"Villanueva-Casanare",
"Mocoa-Putumayo",
"Colón-Putumayo",
"Orito-Putumayo",
"Puerto Asís-Putumayo",
"Puerto Caicedo-Putumayo",
"Puerto Guzmán-Putumayo",
"Puerto Leguízamo-Putumayo",
"Sibundoy-Putumayo",
"San Francisco-Putumayo",
"San Miguel-Putumayo",
"Santiago-Putumayo",
"Valle Del Guamuez-Putumayo",
"Villagarzón-Putumayo",
"San Andrés-Archipiélago de San Andrés, Providencia y Santa Catalina",
"Providencia-Archipiélago de San Andrés, Providencia y Santa Catalina",
"Leticia-Amazonas",
"El Encanto-Amazonas",
"La Chorrera-Amazonas",
"La Pedrera-Amazonas",
"La Victoria-Amazonas",
"Mirití - Paraná-Amazonas",
"Puerto Alegría-Amazonas",
"Puerto Arica-Amazonas",
"Puerto Nariño-Amazonas",
"Puerto Santander-Amazonas",
"Tarapacá-Amazonas",
"Inírida-Guainía",
"Barrancominas-Guainía",
"Mapiripana-Guainía",
"San Felipe-Guainía",
"Puerto Colombia-Guainía",
"La Guadalupe-Guainía",
"Cacahual-Guainía",
"Pana Pana-Guainía",
"Morichal-Guainía",
"San José Del Guaviare-Guaviare",
"Calamar-Guaviare",
"El Retorno-Guaviare",
"Miraflores-Guaviare",
"Mitú-Vaupés",
"Carurú-Vaupés",
"Pacoa-Vaupés",
"Taraira-Vaupés",
"Papunahua-Vaupés",
"Yavaraté-Vaupés",
"Puerto Carreño-Vichada",
"La Primavera-Vichada",
"Santa Rosalía-Vichada",
"Cumaribo-Vichada"


]